### PR TITLE
Some stuff...

### PR DESCRIPTION
**Pull request by Plastel**
New map: Thaumiel and Argus (this one will have it's own sector tree!)

### CODE REVIEW

**Comment by Jasmarkelina** [comment]
accidentally closed pull request

**Comment by Jasmarkelina** [comment]
monument is conflicting tho

**Comment by Plastel** [comment]
Lemme delete the monument so it doesn't conflict

**Comment by Jasmarkelina** [comment]
strange, still conflicting, lemme check your repo

**Comment by Jasmarkelina** [comment]
not sure how i can resolve this

**Comment by Plastel** [comment]
anxiety, guess i'll add Argus again

**Comment by Jasmarkelina** [comment]
kk, while ya do that imma think what imma do for school

**Pull request closed without merging**
